browser=chrome
headless=true
base.url=http://the-internet.herokuapp.com/large
implicit.wait.seconds=0
explicit.wait.seconds=10
benchmark.iterations=50
api.base.uri=http://localhost:8089
api.table.endpoint=/mock/large-table
grid.rows=50
grid.columns=50